using System;
using System.Collections.Generic;
using System.Text;

namespace OuiMailer
{
	public static class Hosts
	{
		public static string Twelve { get { return "012.net.il"; } }
		public static string OneNineOne { get { return "mail.191.biz"; } }
		public static string OneNineOneIt { get { return "mail.191.it"; } }
		public static string Access4Less { get { return "smtp.access4less.net"; } }
		public static string ActiveNetwork { get { return "smtp.activenetwork.it"; } }
		public static string ActrixNetworks { get { return "mail.actrix.co.nz"; } }
		public static string Adelphia { get { return "mail.adelphia.net"; } }
		public static string Akfree { get { return "smtp.akfree.it"; } }
		public static string AlbacomRelay { get { return "relay.albacom.net"; } }
		public static string AlbacomSmtp { get { return "smtp.albacom.net"; } }
		public static string Alcotek { get { return "smtp.alcotek.it"; } }
		public static string alice { get { return "out.aliceposta.it"; } }
		public static string AlicepostaIt { get { return "mail.tin.it"; } }
		public static string Alise { get { return "outmail.f2s.com"; } }
		public static string AOL { get { return "smtp.aol.com"; } }
		public static string Arnet { get { return "smtp.arnet.com.ar"; } }
		public static string Aruba { get { return "smtp.aruba.it"; } }
		public static string ATTWireless { get { return "smtp.attwireless.net"; } }
		public static string ATTWorldnet { get { return "imailhost.worldnet.att.net"; } }
		public static string AtlanetWeblinea { get { return "smtp.weblinea.it"; } }
		public static string AtlanetAtlavia { get { return "smtp.atlavia.it"; } }
		public static string Auna { get { return "smtp.auna.com"; } }
		public static string BahrainTelecommunicationsCompany { get { return "batelco.com.bh"; } }
		public static string BarakITC { get { return "mail.barak.net.il"; } }
		public static string BasilicatanetIt { get { return "mail.basilicatanet.it"; } }
		public static string BellaCi { get { return "bella.ci"; } }
		public static string Bellsouth { get { return "mail.bellsouth.net"; } }
		public static string BezeqInternational { get { return "mail.bezeqint.net"; } }
		public static string Bezeqint { get { return "mail.bezeqint.net"; } }
		public static string Bitstop { get { return "pangasinan.com"; } }
		public static string BluIt { get { return "smtp.blu.it"; } }
		public static string Bluebottle { get { return "mail.bluebottle.com"; } }
		public static string BluelightCom { get { return "smtp.mybluelight.com"; } }
		public static string Bluewin { get { return "mail.bluewin.ch"; } }
		public static string BlueYonder { get { return "smtp.blueyonder.co.uk"; } }
		public static string BolComBr { get { return "smtp.bol.com.br"; } }
		public static string BRTURBO { get { return "smtp.brturbo.com.br"; } }
		public static string BTInternet { get { return "mail.btinternet.com"; } }
		public static string BTOpenworld { get { return "mail.btopenworld.com"; } }
		public static string BTClick { get { return "smtp.btclick.com"; } }
		public static string BTTB { get { return "mail.bttb.net.bd"; } }
		public static string BusinessServe { get { return "smtp.businessserve.co.uk"; } }
		public static string CableOne { get { return "mail.cableone.net"; } }
		public static string Cableinet { get { return "smtp.blueyonder.co.uk"; } }
		public static string Caiway { get { return "smtp.caiway.nl"; } }
		public static string CallsouthBroadband { get { return "smtp2.callsouth.net.nz"; } }
		public static string CallsouthDialUp { get { return "smtp.callsouth.net.nz"; } }
		public static string CantvNet { get { return "mail.cantv.net"; } }
		public static string Cegetel { get { return "smtp.cegetel.net"; } }
		public static string ChariotNetconnect { get { return "mail.vic.chariot.net.au"; } }
		public static string CharterPop { get { return "pop.charter.net"; } }
		public static string CharterMail { get { return "mail.charter.net"; } }
		public static string Cheapnet { get { return "smtp.cheapnet.it"; } }
		public static string ChelloPl { get { return "mail.chello.pl"; } }
		public static string Ciaoweb { get { return "ciaosmtp.ciaoweb.it"; } }
		public static string Cingular { get { return "smtp.mymmode.com"; } }
		public static string Ciudad { get { return "smtp.ciudad.com.ar"; } }
		public static string Claranet { get { return "relay.clara.net"; } }
		public static string ClearNet { get { return "smtp.clear.net.nz"; } }
		public static string Click21 { get { return "smtp.click21.com.br"; } }
		public static string ClubInternet { get { return "smtp.club-internet.fr"; } }
		public static string Collegeclub { get { return "collegeclub.com"; } }
		public static string ColtNetGermany { get { return "smtp.ipmail.colt.net"; } }
		public static string ColumbiaPowerAndWater { get { return "mail.cpws.net"; } }
		public static string Comcast { get { return "smtp.comcast.net"; } }
		public static string CoxCentral { get { return "smtp.central.cox.net"; } }
		public static string CoxEast { get { return "smtp.east.cox.net"; } }
		public static string CoxWest { get { return "smtp.west.cox.net"; } }
		public static string Cultura { get { return "smtp.cultura.com.br"; } }
		public static string CWCom { get { return "smtp.ntlworld.com"; } }
		public static string Datamat { get { return "mail.datamat.it"; } }
		public static string Demon { get { return "post.demon.co.uk"; } }
		public static string DigitelItalia { get { return "smtp.etmail.it"; } }
		public static string Dinajpur { get { return "www.dinajpur.biz"; } }
		public static string DreamNetInternet { get { return "mail.dreamnet.co.nz"; } }
		public static string EarthLink { get { return "smtpauth.earthlink.net"; } }
		public static string Easynet { get { return "smtp.easynet.co.uk"; } }
		public static string EircomNet { get { return "mail2.eircom.net"; } }
		public static string Elitel { get { return "smtp.elitel.biz"; } }
		public static string EmailIt { get { return "smtp.email.it"; } }
		public static string EuronetNL { get { return "smtp.euronet.nl"; } }
		public static string Everybodycanadd { get { return "itsverybad"; } }
		public static string Excite { get { return "smtp.tiscali.it"; } }
		public static string EzySurf { get { return "smtp.ezysurf.co.nz"; } }
		public static string FastMail { get { return "mail.messagingengine.com"; } }
		public static string FastwebSmtp { get { return "smtp.fastweb.it"; } }
		public static string FastwebMailbus { get { return "mailbus.fastweb.it"; } }
		public static string FastwebPop { get { return "pop.fastwebnet.it"; } }
		public static string FastwebNetSmtp { get { return "smtp.fastwebnet.it"; } }
		public static string FibertelComAr { get { return "smtp.fibertel.com.ar"; } }
		public static string Free { get { return "smtp.free.fr"; } }
		public static string FreeTelecom { get { return "smtp.free.fr"; } }
		public static string Freedom2surf { get { return "outmail.f2s.com"; } }
		public static string Freemail { get { return "smtp.freemail.it"; } }
		public static string FreemailIt { get { return "mail.freemail.it"; } }
		public static string FreemailItSupereva { get { return "mail.freemail.it"; } }
		public static string Freenet { get { return "mx.freenet.de"; } }
		public static string FreenetDe { get { return "mx.freenet.de"; } }
		public static string Freeserve { get { return "smtp.freeserve.co.uk"; } }
		public static string GalacticaIt { get { return "smtp.galactica.it"; } }
		public static string Genie { get { return "mail.genie.co.uk"; } }
		public static string GIGA { get { return "smtp.giga.net.tw"; } }
		public static string GlobeNetCommunications { get { return "smtp.globe.net.nz"; } }
		public static string Gmail { get { return "smtp.gmail.com"; } }
		public static string GMX { get { return "mail.gmx.net"; } }
		public static string GoDaddy { get { return "smtpout.secureserver.net"; } }
		public static string GoCom { get { return "smtp.go.com"; } }
		public static string HaierElectronics { get { return "smtp.haier-electronics.com"; } }
		public static string Hinet { get { return "msa.hinet.net"; } }
		public static string HiNet { get { return "ms1.hinet.net"; } }
		public static string Hotmail { get { return "hotmail.co.uk"; } }
		public static string Hotmail2 { get { return "mx2.hotmail.com"; } }
		public static string Hotmail3 { get { return "mx2.hotmail.com"; } }
		public static string Hotmail4 { get { return "mx1.hotmail.com"; } }
		public static string Hotmail5 { get { return "mx1.hotmail.com"; } }
		public static string HotPOPCom { get { return "smtp.hotpop.com"; } }
		public static string I4UInternetServices { get { return "mail.i4u.net.nz"; } }
		public static string IC24 { get { return "smtp.ic24.net"; } }
		public static string IG { get { return "smtp.ig.com.br"; } }
		public static string IHUG { get { return "smtp.ihug.co.nz"; } }
		public static string INET { get { return "inet.it"; } }
		public static string Infinito { get { return "mail.infinito.it"; } }
		public static string InfoStructureGRRTechnology { get { return "smtp.grrtech.com"; } }
		public static string InfoStructureInfoStructure { get { return "smtp.mind.net"; } }
		public static string InfoStructureKlamathFallsInternet { get { return "smtp.kfalls.net"; } }
		public static string InfoStructureMedfordInternet { get { return "smtp.medford.net"; } }
		public static string InsightBB { get { return "mail.insightbb.com"; } }
		public static string Interbusiness { get { return "mail1.cs.interbusiness.it"; } }
		public static string INTERFREE { get { return "mail.interfree.it"; } }
		public static string InternetZahav { get { return "sout.zahav.net.il"; } }
		public static string Internetlibero { get { return "smtp.internetlibero.it"; } }
		public static string InWind { get { return "mail.inwind.it"; } }
		public static string IOL { get { return "mail.iol.it"; } }
		public static string Iomart { get { return "smtp.domain.ext"; } }
		public static string IPrimusAustralia { get { return "smtp.iprimus.com.au"; } }
		public static string Iprolink { get { return "smtp.iprolink.co.nz"; } }
		public static string IStruzioneIt { get { return "istruzione.it"; } }
		public static string ItalyMAIL { get { return "mail.italymail.biz"; } }
		public static string IxpresCom { get { return "smtp.ixpres.com"; } }
		public static string Jumpy { get { return "mail.jumpy.it"; } }
		public static string Juno { get { return "smtp.juno.com"; } }
		public static string Katamail { get { return "smtp.katamail.com"; } }
		public static string Kataweb { get { return "smtp.katamail.com"; } }
		public static string LaPoste { get { return "smtp.laposte.net"; } }
		public static string LeNeuf { get { return "smtp.neuf.fr"; } }
		public static string Libero { get { return "mail.libero.it"; } }
		public static string Lillinet { get { return "smtp.weblinea.it"; } }
		public static string Lineone { get { return "smtp.lineone.net"; } }
		public static string Lycos { get { return "smtp.lycos.co.uk"; } }
		public static string LycosIt { get { return "smtp.lycos.it"; } }
		public static string MacCom { get { return "smtp.mac.com"; } }
		public static string Madasafish { get { return "smtp.madasafish.com"; } }
		public static string MailQuizilNet { get { return "mail.quizil.net"; } }
		public static string MailRu { get { return "smtp.mail.ru"; } }
		public static string Mailsnare { get { return "mail.mailsnare.net"; } }
		public static string MaktoobMail { get { return "mira0.maktoob.com"; } }
		public static string McLink { get { return "mail.mclink.it"; } }
		public static string Mediacom { get { return "mail.mchsi.com"; } }
		public static string Mistral { get { return "smtp.mistral.co.uk"; } }
		public static string Momax { get { return "smtp.momax.it"; } }
		public static string Ms15HinetNet { get { return "ms15.hinet.net"; } }
		public static string MsoftIt { get { return "smtp.weblinea.it"; } }
		public static string Mtel { get { return "mail.mtel.net"; } }
		public static string NamesToday { get { return "smtp.namestoday.ws"; } }
		public static string NerimNet { get { return "astralblue@nerim.net"; } }
		public static string Netcabo { get { return "smtp.netcabo.pt"; } }
		public static string NetexploraChile { get { return "mail.netexplora.com"; } }
		public static string Netlink { get { return "mail.netlink.co.nz"; } }
		public static string Netscape { get { return "smtp.isp.netscape.com"; } }
		public static string Netscapeonline { get { return "mailhost.netscapeonline.co.uk"; } }
		public static string netvigator { get { return "mail.netvigator.com"; } }
		public static string Netvisão { get { return "mail.netvisao.pt"; } }
		public static string NetZeroCom { get { return "smtp.netzero.com"; } }
		public static string NeufTelecom { get { return "smtp.neuf.fr"; } }
		public static string NGI { get { return "smtp.ngi.it"; } }
		public static string Nildram { get { return "smtp.nildram.co.uk"; } }
		public static string Noos { get { return "smtp.noos.fr"; } }
		public static string Novis { get { return "mail.novis.pt"; } }
		public static string NTL { get { return "smtp.ntlworld.com"; } }
		public static string NTLWorld { get { return "smtp.ntlworld.com"; } }
		public static string O2 { get { return "relay.o2broadband.co.uk"; } }
		public static string OneTel { get { return "mail.onetel.net.uk"; } }
		public static string OnoFrance { get { return "wanadoo.fr"; } }
		public static string OnoCom { get { return "smtp.ono.com"; } }
		public static string Optonline { get { return "mail.optonline.net"; } }
		public static string Orcon { get { return "mail.orcon.net.nz"; } }
		public static string OutgoingVerizonNet { get { return "tchrshelli"; } }
		public static string PCTS { get { return "ns.pcts.sk"; } }
		public static string ParadiseNet { get { return "smtp.paradise.net.nz"; } }
		public static string PCHome { get { return "smtp.pchome.com.tw"; } }
		public static string PeoplePCSmtpAuth { get { return "smtpauth.peoplepc.com"; } }
		public static string PeoplePCMail { get { return "mail.peoplepc.com"; } }
		public static string PipexDSL { get { return "smtp.dsl.pipex.com"; } }
		public static string PipexDial { get { return "smtp.dial.pipex.com"; } }
		public static string Pixius { get { return "smtp.citilink.com"; } }
		public static string PostMan { get { return "mail.postman.net"; } }
		public static string PosteIt { get { return "relay.poste.it"; } }
		public static string PostinoIt { get { return "smtp.postino.it"; } }
		public static string Previdencia { get { return "kiwi.previdencia.gov.br"; } }
		public static string ProdigyXasa { get { return "xasa.com"; } }
		public static string Prodigy { get { return "smtp.prodigy.net.mx"; } }
		public static string PromoIt { get { return "smtp.promo.it"; } }
		public static string Purplenet { get { return "smtp.purplenet.co.uk"; } }
		public static string Quipo { get { return "quipo.it"; } }
		public static string R { get { return "smtp.mundo-r.com"; } }
		public static string RadioDeejayMail { get { return "smtp.deejaymail.it"; } }
		public static string RCP { get { return "amauta.rcp.net.pe"; } }
		public static string Reteitaly { get { return "smtp.reteitaly.com"; } }
		public static string Rogers { get { return "smtp.broadband.rogers.com"; } }
		public static string RunBox { get { return "smtp.runbox.com"; } }
		public static string Sapo { get { return "mx.sapo.pt"; } }
		public static string SBCGlobal { get { return "smtp.flash.yahoo.com"; } }
		public static string SBCGlobal2 { get { return "smtp.nvbell.yahoo.com"; } }
		public static string SBCGlobal3 { get { return "smtp.pacbell.yahoo.com"; } }
		public static string SBCGlobal4 { get { return "smtp.sbcglobal.yahoo.com"; } }
		public static string SBCGlobal5 { get { return "smtp.prodigy.yahoo.com"; } }
		public static string SBCGlobal6 { get { return "smtp.wans.yahoo.com"; } }
		public static string SBCGlobal7 { get { return "smtp.snet.yahoo.com"; } }
		public static string SBCGlobal8 { get { return "smtp.swbell.yahoo.com"; } }
		public static string SBCGlobal9 { get { return "smtp.ameritech.yahoo.com"; } }
		public static string SBCYahooDSL { get { return "smtp.sbcglobal.yahoo.com"; } }
		public static string SbcyahooDSL { get { return "smtp.sbcglobal.yahoo.com"; } }
		public static string ScarletOrScarletBe { get { return "smtp.scarlet.be"; } }
		public static string ScreamingNet { get { return "smtp.tiscali.co.uk"; } }
		public static string SFR { get { return "smtp-auth.sfr.fr"; } }
		public static string ShawCanada { get { return "shawmail.cg.shawcable.net"; } }
		public static string ShylexTelecomunicaciones { get { return "smtp.shylex.net"; } }
		public static string SiFreeIt { get { return "smtp.simail.it"; } }
		public static string SifyCom { get { return "mail.satyam.net.in"; } }
		public static string Skynet { get { return "relay.skynet.be"; } }
		public static string SkynetBe { get { return "relay.skynet.be"; } }
		public static string Slingshot { get { return "smtp.slingshot.co.nz"; } }
		public static string SofthomeNet { get { return "mail.softhome.net"; } }
		public static string SouthNet { get { return "smtp.southnet.co.nz"; } }
		public static string SouthwesternBell { get { return "mail.swbell.net"; } }
		public static string SprintPCS { get { return "smtp.sprintpcs.com"; } }
		public static string Spymac { get { return "mail.spymac.com"; } }
		public static string StofaNetDK { get { return "mail1.stofanet.dk"; } }
		public static string Sunrise { get { return "smtp.sunrise.ch"; } }
		public static string Supanet { get { return "smtp.supanet.com"; } }
		public static string Supereva { get { return "mail.supereva.it"; } }
		public static string SuperFreeIt { get { return "smtp.superfree.it"; } }
		public static string Sympatico { get { return "smtp1.sympatico.ca"; } }
		public static string TagComunicazioni { get { return "64.94.0.31"; } }
		public static string TalkTalk { get { return "smtp.TalkTalk.net"; } }
		public static string TariffeIt { get { return "smtp.tariffenet.it"; } }
		public static string TDC { get { return "backup-mx.post.tele.dk"; } }
		public static string Tele2Fr { get { return "smtp.tele2.fr"; } }
		public static string Tele2It { get { return "smtp.tele2.it"; } }
		public static string Tele2Internet { get { return "virtual.everyday.com"; } }
		public static string telecom { get { return "mail.cs.interbusiness.it"; } }
		public static string Telecom { get { return "mail.tin.it"; } }
		public static string TelecomADSLBusiness { get { return "smtp.191.it"; } }
		public static string TelecomADSLBusiness2 { get { return "mail.191.it"; } }
		public static string TelecomItalia { get { return "191.it"; } }
		public static string TelecomSmart { get { return "mail.tuttopmi.it"; } }
		public static string TelecomXtra { get { return "smtp.xtra.co.nz"; } }
		public static string TeleconomyInternet { get { return "mail.191.it"; } }
		public static string TELEDISNETBE { get { return "mail.teledisnet.be"; } }
		public static string Telefonica { get { return "smtp.telefonica.net"; } }
		public static string TelenetBelgium { get { return "uit.telenet.be"; } }
		public static string Telepac { get { return "smtp.telepac.pt"; } }
		public static string TelepacADSLPortugal { get { return "smtp.telepac.pt"; } }
		public static string Telewest { get { return "smtp.blueyonder.co.uk"; } }
		public static string Telkom { get { return "smpt.telkom.net"; } }
		public static string TelkomsaNet { get { return "smtp.telkomsa.net"; } }
		public static string Telus { get { return "smtp.telus.net"; } }
		public static string TelusNet { get { return "mail.telus.net"; } }
		public static string TelviaIt { get { return "smtp.telvia.it"; } }
		public static string Terra { get { return "smtp.terra.es"; } }
		public static string TerraBR { get { return "smtp.sao.terra.com.br"; } }
		public static string TerraBRRecife { get { return "smtp.rec.terra.com.br"; } }
		public static string TerraEspaña { get { return "mailhost.terra.es"; } }
		public static string TerraEspaña2 { get { return "smtp.mailhost.terra.es"; } }
		public static string Tesconet { get { return "mail.tesco.net"; } }
		public static string TIMIt { get { return "mail.posta.tim.it"; } }
		public static string TimenetADSL { get { return "smtp2.xdslnet.it"; } }
		public static string TimeWarner { get { return "(Unknown At This Time)"; } }
		public static string TinIt { get { return "out.virgilio.it"; } }
		public static string TINITFree { get { return "mail.clubnet.tin.it"; } }
		public static string TiscaliCoUk { get { return "smtp.tiscali.co.uk"; } }
		public static string TiscaliIt { get { return "smtp.tiscali.it"; } }
		public static string TiscaliDe { get { return "smtp.tiscali.de"; } }
		public static string tiscaliEs { get { return "smtp.tiscali.es"; } }
		public static string TiscaliNl { get { return "smtp.tiscali.nl"; } }
		public static string Tnet { get { return "mail.tnet.it"; } }
		public static string TOnline { get { return "mailto.t-online.de"; } }
		public static string Totalise { get { return "mail.totalise.co.uk"; } }
		public static string Tre { get { return "smtp.tre.it"; } }
		public static string Tugamail { get { return "mail.tugamail.com"; } }
		public static string TuttoGratisIt { get { return "smtp.eutelia.it"; } }
		public static string Tvtel { get { return "tvtel.pt"; } }
		public static string UKGateway { get { return "smtp.ukgateway.net"; } }
		public static string Unitedemailsystems { get { return "unitedemailsystems.com"; } }
		public static string UnitedemailsystemsSmtp { get { return "smtp.unitedemailsystems.com"; } }
		public static string UOL { get { return "smtp.uol.com.br"; } }
		public static string UOLSinectisArgentina { get { return "relay.uolsinectis.com.ar"; } }
		public static string USCable { get { return "smtp.warpdriveonline.com"; } }
		public static string USANet { get { return "smtp.postoffice.net"; } }
		public static string UtentiInterbusinessTelecom { get { return "mail.cs.interbusiness.it"; } }
		public static string UtopiaSystems { get { return "smtp.utopiasystems.net"; } }
		public static string UtuFi { get { return "smtp.utu.fi"; } }
		public static string V21 { get { return "smtp.v21.co.uk"; } }
		public static string VerizonDSL { get { return "outgoing.verizon.net"; } }
		public static string Videobank { get { return "videobank.it"; } }
		public static string Virgilio { get { return "out.virgilio.it"; } }
		public static string Virgin { get { return "smtp.virgin.net"; } }
		public static string Vispa { get { return "mail.vispa.com"; } }
		public static string Vivacity { get { return "pop.Vivacity.it"; } }
		public static string VodafoneIt { get { return "smtpmail.vodafone.it"; } }
		public static string Waitrose { get { return "smtpmail.waitrose.com"; } }
		public static string Wanadoo { get { return "smtp.wanadooadsl.net"; } }
		public static string WanadooFr { get { return "smtp.wanadoo.fr"; } }
		public static string WanadooEspaña { get { return "smtp.wanadoo.es"; } }
		public static string WanadooNl { get { return "smtp.wanadoo.nl"; } }
		public static string WebDe { get { return "smtp.web.de"; } }
		public static string WebmailIs { get { return "smtp.emailsrvr.com"; } }
		public static string WindowsLiveHotmail { get { return "smtp.live.com"; } }
		public static string WooowIt { get { return "smtp.wooow.it"; } }
		public static string WorldNet { get { return "mail.world-net.co.nz"; } }
		public static string Worldonline { get { return "smtp.tiscali.co.uk"; } }
		public static string QosNetIl { get { return "mail.qos.net.il"; } }
		public static string TolIt { get { return "smtp-tol.it"; } }
		public static string TolIt2 { get { return "smtp.tol.it"; } }
		public static string XPrivat { get { return "mail.x-privat.org"; } }
		public static string XS4ALL { get { return "smtp.xs4all.nl"; } }
		public static string XS4allNl { get { return "mail.xs4all.nl"; } }
		public static string Xtra { get { return "smtp.xtra.co.nz"; } }
		public static string YaCom { get { return "smtp.ya.com"; } }
		public static string YaComADSL { get { return "smtp2.adsl.ya.com"; } }
		public static string YahooComCs { get { return "smtp.mail.yahoo.com.cn"; } }
		public static string YahooEs { get { return "yahoo.es"; } }
		public static string Yahoo { get { return "smtp.mail.yahoo.com"; } }
		public static string YahooAuthenticationNeeded { get { return "smtp.mail.yahoo.com"; } }
		public static string YahooArgentina { get { return "smtp.mail.yahoo.com.ar"; } }
		public static string YahooUk { get { return "smtp.mail.yahoo.co.uk"; } }
		public static string YahooComTw { get { return "smtp.mail.yahoo.com.tw"; } }
		public static string YahooCom { get { return "stmp.mail.yahoo.com"; } }
		public static string YahooDe { get { return "smtp.mail.yahoo.de"; } }
		public static string YahooEs2 { get { return "smtp.correo.yahoo.es"; } }
		public static string YahooIt { get { return "smtp.mail.yahoo.it"; } }
		public static string ZeelandNet { get { return "mail.zeelandnet.nl"; } }
		public static string ZeroAdJp { get { return "zero.ad.jp"; } }
		public static string Zonnet { get { return "smtp.zonnet.nl"; } }
	}
}
